#!/usr/bin/env sh
"$(dirname -- "$0")/_/husky.sh"
# npm run test

# Run lint-staged
echo "[Husky] Running lint-staged"
npx lint-staged

# Run commitlint
echo "[Husky] Running commitlint"
npx --no -- commitlint --edit "$1"
